import json
from html import escape
from typing import Any, Dict, List, Tuple


class DocumentationGenerator:
    """Generate developer-readable Markdown and HTML from extracted endpoint metadata."""

    @staticmethod
    def generate_markdown(
        endpoints: List[Dict[str, Any]], title: str = "Generated API Documentation"
    ) -> str:
        lines = [
            f"# {title}",
            "",
            f"Generated endpoints: **{len(endpoints)}**",
            "",
            "## Overview",
            "",
            "This documentation was generated by analyzing source code.",
            "Only metadata explicitly detected from source code is included.",
            "Missing sections indicate that metadata was not found in the source.",
            "",
            "## Endpoints",
            "",
        ]

        for endpoint in DocumentationGenerator._sort_endpoints(endpoints):
            method = endpoint.get("method", "GET")
            path = endpoint.get("path", "/")
            lines.extend(
                [
                    f"### `{method} {path}`",
                    "",
                    f"- Framework: `{DocumentationGenerator._get_framework(endpoint)}`",
                    f"- Handler: `{DocumentationGenerator._get_handler(endpoint)}`",
                    f"- Source: `{DocumentationGenerator._get_source(endpoint)}`",
                    f"- Summary: {endpoint.get('summary', '')}",
                    "",
                    endpoint.get("description", ""),
                    "",
                ]
            )

            DocumentationGenerator._append_markdown_parameters(lines, endpoint)
            DocumentationGenerator._append_markdown_request_body(lines, endpoint)
            DocumentationGenerator._append_markdown_pagination(lines, endpoint)
            DocumentationGenerator._append_markdown_request_example(lines, endpoint)
            DocumentationGenerator._append_markdown_responses(lines, endpoint)
            DocumentationGenerator._append_markdown_ai_notes(lines, endpoint)
            lines.append("---")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def generate_html(
        endpoints: List[Dict[str, Any]], title: str = "Generated API Documentation"
    ) -> str:
        sorted_endpoints = DocumentationGenerator._sort_endpoints(endpoints)
        endpoint_cards = "\n".join(
            DocumentationGenerator._endpoint_card(endpoint, idx)
            for idx, endpoint in enumerate(sorted_endpoints)
        )
        frameworks = sorted(
            {str(DocumentationGenerator._get_framework(endpoint)) for endpoint in sorted_endpoints}
        )
        # Remove "Unknown" from the set if there are other frameworks
        frameworks_filtered = {f for f in frameworks if f != "Unknown"}
        framework_label = ", ".join(sorted(frameworks_filtered)[:3]) if frameworks_filtered else "Detected API"

        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <style>
    :root {{ color-scheme: light; --bg:#f8fbff; --panel:#ffffff; --panel-2:#f1f6fd; --line:#d7e3f3; --text:#0f172a; --muted:#5f6f86; --primary:#1d4ed8; --primary-2:#2563eb; --danger:#dc2626; --warn:#d97706; --soft:#eaf2ff; }}
    body.dark {{ color-scheme: dark; --bg:#10151f; --panel:#151d2a; --panel-2:#1d2736; --line:#344154; --text:#edf2f7; --muted:#a6b4c6; --primary:#7db4ff; --primary-2:#9bc5ff; --danger:#f87171; --warn:#fbbf24; --soft:#223249; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; font-family:Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background:var(--bg); color:var(--text); }}
    code, pre {{ font-family:"JetBrains Mono", "SFMono-Regular", Consolas, monospace; }}
    a {{ color:inherit; text-decoration:none; }}
    .layout {{ display:flex; height:100vh; overflow:hidden; }}
    .sidebar {{ width:292px; background:#ffffff; border-right:1px solid var(--line); overflow:auto; flex-shrink:0; }}
    .sidebar-header {{ padding:20px; border-bottom:1px solid var(--line); background:#f5f8fe; }}
    .sidebar-header h2 {{ margin:0 0 12px; color:var(--primary); font-size:16px; }}
    .search-input {{ width:100%; border:1px solid var(--line); border-radius:6px; background:#fff; color:var(--text); padding:10px 12px; font-size:12px; outline-color:var(--primary); }}
    .nav-section-label {{ padding:14px 16px 6px; color:#72819a; font-size:10px; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }}
    .doc-nav-list, .group-items {{ list-style:none; margin:0; padding:0; }}
    .nav-item a {{ display:flex; align-items:center; gap:8px; padding:7px 16px; color:var(--muted); font-size:12px; border-left:2px solid transparent; }}
    .nav-item a:hover {{ color:var(--primary); background:var(--soft); border-left-color:var(--primary); }}
    .method-badge {{ min-width:42px; text-align:center; padding:3px 7px; border-radius:4px; color:#fff; font-size:10px; font-weight:800; text-transform:uppercase; }}
    .badge-get {{ background:#1d4ed8; }} .badge-post {{ background:#2563eb; }} .badge-put {{ background:#0f172a; }} .badge-delete {{ background:#dc2626; }} .badge-patch {{ background:#4f46e5; }} .badge-other {{ background:#64748b; }}
    .group-toggle {{ width:100%; border:0; background:transparent; color:var(--text); display:flex; align-items:center; gap:8px; padding:9px 16px; cursor:pointer; font-weight:700; }}
    .toggle-arrow {{ transition:transform .15s; }} .group-items:not(.show) {{ display:none; }} .badge-count {{ margin-left:auto; color:var(--primary); border:1px solid var(--line); border-radius:999px; padding:1px 7px; font-size:10px; }}
    .content-area {{ flex:1; display:flex; flex-direction:column; overflow:hidden; }}
    .content-left {{ flex:1; display:flex; flex-direction:column; overflow:hidden; height:100%; }}
    .content-header {{ padding:24px 32px; background:var(--panel); border-bottom:1px solid var(--line); display:flex; align-items:center; justify-content:space-between; gap:16px; }}
    .header-info {{ display:flex; align-items:center; gap:12px; flex-wrap:wrap; }}
    h1 {{ margin:0; color:var(--primary); font-size:26px; line-height:1.2; }}
    .version, .fw-badge {{ border:1px solid var(--line); border-radius:4px; padding:3px 9px; color:var(--muted); font-size:11px; }}
    .version {{ color:#05130b; background:var(--primary); border-color:var(--primary); font-weight:800; }}
    .content-body {{ flex:1; overflow:auto; padding:24px 32px; scroll-behavior:smooth; }}
    .doc-section, .endpoint {{ background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:22px; margin-bottom:18px; }}
    .section-header {{ color:var(--primary); border-bottom:1px solid var(--line); padding-bottom:12px; margin-bottom:16px; font-weight:800; display:flex; align-items:center; gap:10px; }}
    .section-desc, .endpoint-description, .empty {{ color:var(--muted); font-size:13px; line-height:1.6; }}
    .overview-grid {{ display:grid; grid-template-columns:repeat(auto-fill, minmax(180px, 1fr)); gap:12px; }}
    .ov-card {{ background:var(--bg); border:1px solid var(--line); border-radius:6px; padding:12px; }}
    .ov-card.full-width {{ grid-column:1/-1; }}
    .ov-label {{ display:block; color:#7f9d8c; font-size:10px; font-weight:800; text-transform:uppercase; margin-bottom:5px; letter-spacing:.05em; }}
    .ov-value, .ov-url {{ color:var(--text); font-size:13px; overflow-wrap:anywhere; }}
    .endpoint-header {{ display:flex; justify-content:space-between; gap:14px; align-items:flex-start; margin:-22px -22px 12px; padding:14px 22px; background:var(--panel); border-bottom:1px solid var(--line); position:sticky; top:0; z-index:5; }}
    .endpoint-title {{ display:flex; align-items:center; gap:10px; flex-wrap:wrap; min-width:0; }}
    .endpoint-path {{ background:var(--bg); color:var(--primary); padding:5px 10px; border-radius:4px; font-size:13px; font-weight:700; overflow-wrap:anywhere; }}
    .endpoint-summary {{ margin:0 0 6px; color:var(--text); font-weight:800; font-size:14px; }}
    .endpoint-meta-line {{ display:flex; flex-wrap:wrap; gap:5px; margin:8px 0 12px; }}
    .meta-chip, .tag-chip {{ border:1px solid var(--line); border-radius:4px; padding:2px 7px; font-size:10px; color:var(--muted); }}
    .tag-chip {{ color:var(--primary); background:var(--soft); }}
    .detail-section {{ border:1px solid var(--line); border-radius:5px; overflow:hidden; margin-top:9px; }}
    .detail-section summary {{ cursor:pointer; list-style:none; background:#f5f8fe; color:var(--text); padding:10px 14px; font-weight:800; font-size:12px; }}
    .detail-section summary::-webkit-details-marker {{ display:none; }}
    .detail-section[open] summary, .detail-section summary:hover {{ color:var(--primary); background:var(--soft); }}
    .section-content {{ background:var(--bg); border-top:1px solid var(--line); padding:14px; overflow:auto; }}
    table {{ width:100%; border-collapse:collapse; font-size:12px; }}
    th, td {{ border:1px solid var(--line); text-align:left; vertical-align:top; padding:8px 10px; }}
    th {{ color:var(--primary); background:var(--soft); }}
    .req-yes {{ color:var(--primary-2); font-weight:800; }} .req-no {{ color:var(--muted); }}
    .response-item {{ margin-bottom:12px; }}
    .response-code {{ display:inline-block; min-width:44px; color:#fff; background:var(--primary); border-radius:4px; padding:3px 8px; font-size:12px; }}
    .error-code {{ color:#fff; background:var(--danger); }}
    .response-desc {{ display:inline; margin-left:8px; color:var(--text); }}
    .section-label {{ color:var(--primary); font-size:11px; font-weight:800; text-transform:uppercase; margin:12px 0 6px; }}
    pre.json {{ margin:0; padding:14px; border:1px solid var(--line); border-radius:6px; background:#ffffff; color:#1e3a8a; overflow:auto; white-space:pre-wrap; word-break:break-word; font-size:12px; line-height:1.55; }}
    body.dark pre.json {{ background:#0d1320; color:#d6e8ff; }}
    .tool-btn {{ border:1px solid var(--line); border-radius:5px; background:var(--panel); color:var(--text); padding:7px 10px; cursor:pointer; font-size:12px; font-weight:700; }}
    .tool-btn:hover {{ border-color:var(--primary); color:var(--primary); }}
    .section-tools {{ display:flex; justify-content:flex-end; margin-bottom:8px; }}
    .scroll-top-btn {{
      position: fixed;
      bottom: 24px;
      right: 24px;
      width: 44px;
      height: 44px;
      border-radius: 50%;
      background: var(--primary);
      color: #fff;
      border: none;
      box-shadow: 0 4px 12px rgba(29, 78, 216, 0.3);
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0;
      visibility: hidden;
      transition: opacity 0.3s, visibility 0.3s, transform 0.2s, background-color 0.2s;
      z-index: 1000;
    }}
    .scroll-top-btn.show {{
      opacity: 1;
      visibility: visible;
    }}
    .scroll-top-btn:hover {{
      background: var(--primary-2);
      transform: translateY(-2px);
    }}
    .scroll-top-btn:active {{
      transform: translateY(0);
    }}
    @media (max-width: 980px) {{ .layout {{ height:auto; min-height:100vh; }} .sidebar {{ display:none; }} .content-area {{ display:block; }} }}
  </style>
</head>
<body>
  <div class="layout">
    <aside class="sidebar">
      <div class="sidebar-header">
        <h2>API Documentation</h2>
        <input class="search-input" type="text" placeholder="Search endpoints..." onkeyup="filterSidebar(this.value)" />
      </div>
      <div class="sidebar-menu">
        <div class="nav-section-label">Documentation</div>
        <ul class="doc-nav-list">
          <li class="nav-item"><a href="#section-overview">Overview</a></li>
        </ul>
        <div class="nav-section-label">Endpoints</div>
        {DocumentationGenerator._sidebar_groups(sorted_endpoints)}
      </div>
    </aside>
    <main class="content-area">
      <section class="content-left">
        <header class="content-header">
          <div class="header-info">
            <h1>{escape(title)}</h1>
            <span class="fw-badge">{escape(framework_label)}</span>
          </div>
          <button class="tool-btn" onclick="toggleTheme()">Theme</button>
        </header>
        <div class="content-body">
          {DocumentationGenerator._overview_section(sorted_endpoints, title)}
          <div class="doc-section" id="section-endpoints">
            <div class="section-header">Endpoints</div>
            {endpoint_cards or '<p class="empty">No endpoints detected.</p>'}
          </div>
        </div>
      </section>
    </main>
  </div>
  <button class="scroll-top-btn" id="scrollTopBtn" onclick="scrollToTop()" aria-label="Scroll to top">
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
      <polyline points="18 15 12 9 6 15"></polyline>
    </svg>
  </button>
  <script>
    function filterSidebar(q) {{
      const needle = q.toLowerCase();
      document.querySelectorAll(".sidebar .nav-item").forEach(item => {{
        item.style.display = item.textContent.toLowerCase().includes(needle) ? "" : "none";
      }});
    }}
    function toggleGroup(idx) {{
      const list = document.getElementById("items-" + idx);
      const arrow = document.getElementById("arrow-" + idx);
      if (list) list.classList.toggle("show");
      if (arrow) arrow.style.transform = list && list.classList.contains("show") ? "rotate(90deg)" : "rotate(0deg)";
    }}
    
    // Scroll handling
    const scrollBtn = document.getElementById('scrollTopBtn');
    const contentBody = document.querySelector('.content-body');

    function handleScroll() {{
      const scrollTop = contentBody ? contentBody.scrollTop : 0;
      const windowScrollTop = window.scrollY || document.documentElement.scrollTop;
      if (scrollTop > 300 || windowScrollTop > 300) {{
        scrollBtn.classList.add('show');
      }} else {{
        scrollBtn.classList.remove('show');
      }}
    }}

    if (contentBody) {{
      contentBody.addEventListener('scroll', handleScroll);
    }}
    window.addEventListener('scroll', handleScroll);

    function scrollToTop() {{
      if (contentBody) {{
        contentBody.scrollTo({{ top: 0, behavior: 'smooth' }});
      }}
      window.scrollTo({{ top: 0, behavior: 'smooth' }});
    }}

    function toggleTheme() {{
      document.body.classList.toggle('dark');
    }}

    function copyBlock(id) {{
      const node = document.getElementById(id);
      if (!node) return;
      navigator.clipboard.writeText(node.textContent || '');
    }}

    // Handle hash links smooth scrolling inside overflow container
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {{
      anchor.addEventListener('click', function (e) {{
        e.preventDefault();
        const targetId = this.getAttribute('href');
        if (targetId === '#') return;
        
        const targetElement = document.querySelector(targetId);
        if (targetElement) {{
          if (contentBody && window.getComputedStyle(contentBody).overflowY === 'auto') {{
            const containerRect = contentBody.getBoundingClientRect();
            const elementRect = targetElement.getBoundingClientRect();
            const relativeTop = elementRect.top - containerRect.top + contentBody.scrollTop;
            contentBody.scrollTo({{
              top: relativeTop,
              behavior: 'smooth'
            }});
          }} else {{
            targetElement.scrollIntoView({{ behavior: 'smooth' }});
          }}
          history.pushState(null, null, targetId);
        }}
      }});
    }});
  </script>
</body>
</html>
"""

    @staticmethod
    def _append_markdown_parameters(lines: List[str], endpoint: Dict[str, Any]):
        params = []
        for location, key in (("path", "path_params"), ("query", "query_params"), ("header", "headers")):
            for param in endpoint.get(key, []) or []:
                params.append((location, param))

        lines.append("#### Parameters")
        if not params:
            lines.extend(["No parameters detected.", ""])
            return

        lines.extend(["| Name | In | Type | Required | Constraints |", "| --- | --- | --- | --- | --- |"])
        for location, param in params:
            lines.append(
                f"| `{param.get('name', '')}` | `{location}` | `{DocumentationGenerator._schema_type(param)}` | `{bool(param.get('required'))}` | {DocumentationGenerator._schema_constraints(param)} |"
            )
        lines.append("")

    @staticmethod
    def _append_markdown_request_body(lines: List[str], endpoint: Dict[str, Any]):
        request_body = endpoint.get("request_body")
        lines.append("#### Request Body")
        if not request_body:
            lines.extend(["No request body detected.", ""])
            return

        lines.append(f"Model: `{request_body.get('model', 'object')}`")
        DocumentationGenerator._append_markdown_schema(lines, request_body.get("schema"))

    @staticmethod
    def _append_markdown_pagination(lines: List[str], endpoint: Dict[str, Any]):
        pagination = DocumentationGenerator._pagination_info(endpoint)
        if not pagination:
            return

        lines.extend(["#### Pagination", ""])
        if pagination["detected"]:
            lines.append("Detected pagination-related query parameters:")
            lines.extend(["| Parameter | Type | Required |", "| --- | --- | --- |"])
            for param in pagination["params"]:
                lines.append(
                    f"| `{param.get('name', '')}` | `{DocumentationGenerator._schema_type(param)}` | `{bool(param.get('required'))}` |"
                )
        else:
            lines.append("This looks like a list endpoint, but no explicit pagination parameters were detected. Document `limit`, `offset`, `page`, or `cursor` before exposing this endpoint at scale.")
        lines.append("")

    @staticmethod
    def _append_markdown_request_example(lines: List[str], endpoint: Dict[str, Any]):
        lines.extend(["#### Request Example", "", "```bash"])
        lines.append(DocumentationGenerator._curl_example(endpoint))
        lines.extend(["```", ""])

    @staticmethod
    def _append_markdown_responses(lines: List[str], endpoint: Dict[str, Any]):
        responses = endpoint.get("responses", []) or []
        lines.append("#### Responses")
        if not responses:
            lines.extend(["No responses detected.", ""])
            return

        for response in responses:
            lines.append(
                f"- `{response.get('status_code', 200)}`: {response.get('description') or response.get('message') or 'Response'}"
            )
            if response.get("model"):
                lines.append(f"  - Model: `{response.get('model')}`")
            if response.get("schema"):
                DocumentationGenerator._append_markdown_schema(lines, response.get("schema"), indent="  ")
            if 200 <= DocumentationGenerator._status_code(response) < 300 and DocumentationGenerator._status_code(response) != 204:
                sample = DocumentationGenerator._sample_from_schema(response.get("schema"))
                if sample is not None:
                    lines.extend(["  - Success example:", ""])
                    lines.append("```json")
                    lines.append(json.dumps(sample, indent=2))
                    lines.append("```")
        lines.append("")

    @staticmethod
    def _append_markdown_schema(lines: List[str], schema: Dict[str, Any], indent: str = ""):
        schema = DocumentationGenerator._schema_object(schema)
        if not schema or not schema.get("properties"):
            lines.append("")
            return

        lines.extend(
            [
                f"{indent}| Field | Type | Required | Nullable | Constraints | Enum |",
                f"{indent}| --- | --- | --- | --- | --- | --- |",
            ]
        )
        required = set(schema.get("required", []))
        for field, field_schema in schema.get("properties", {}).items():
            lines.append(
                f"{indent}| `{field}` | `{DocumentationGenerator._schema_type(field_schema)}` | `{field in required}` | `{bool(field_schema.get('nullable'))}` | {DocumentationGenerator._schema_constraints(field_schema)} | {DocumentationGenerator._schema_enum(field_schema)} |"
            )
        lines.append("")

    @staticmethod
    def _append_markdown_ai_notes(lines: List[str], endpoint: Dict[str, Any]):
        ai_notes = endpoint.get("ai_notes")
        if not ai_notes:
            return

        lines.extend(["#### AI Notes", ""])
        for label, key in (("Request", "request"), ("Response", "response"), ("Errors", "errors")):
            value = ai_notes.get(key)
            if value:
                lines.append(f"- {label}: {value}")
        lines.append("")

    @staticmethod
    def _endpoint_card(endpoint: Dict[str, Any], idx: int = 0) -> str:
        method_raw = str(endpoint.get("method", "GET")).upper()
        method = escape(method_raw)
        path = escape(str(endpoint.get("path", "/")))
        handler = escape(str(DocumentationGenerator._get_handler(endpoint)))
        source = escape(str(DocumentationGenerator._get_source(endpoint)))
        summary = escape(str(endpoint.get("summary") or "No endpoint summary was detected."))
        description = escape(str(endpoint.get("description") or "No endpoint description was detected."))
        framework = escape(str(DocumentationGenerator._get_framework(endpoint)))
        
        # Extract detailed metadata
        status_codes_html = DocumentationGenerator._html_status_codes(endpoint)
        path_params_html = DocumentationGenerator._html_path_parameters(endpoint)
        security_html = DocumentationGenerator._html_security(endpoint)

        return f"""
    <section class="endpoint" id="endpoint-{idx}">
      <div class="endpoint-header">
        <div class="endpoint-title">
          <span class="method-badge {DocumentationGenerator._method_badge_class(method_raw)}">{method}</span>
          <code class="endpoint-path">{path}</code>
        </div>
      </div>
      <p class="endpoint-summary">{summary}</p>
      <p class="endpoint-description">{description}</p>
      <div class="endpoint-meta-line">
        <span class="meta-chip">Handler: {handler}</span>
        <span class="meta-chip">Source: {source}</span>
        <span class="tag-chip">{framework}</span>
      </div>
      {path_params_html}
      {security_html}
      {status_codes_html}
      {DocumentationGenerator._html_parameters(endpoint)}
      {DocumentationGenerator._html_request_body(endpoint)}
      {DocumentationGenerator._html_pagination(endpoint)}
      {DocumentationGenerator._html_request_example(endpoint)}
      {DocumentationGenerator._html_responses(endpoint)}
      {DocumentationGenerator._html_error_responses(endpoint)}
      {DocumentationGenerator._html_ai_notes(endpoint)}
    </section>
"""

    @staticmethod
    def _html_parameters(endpoint: Dict[str, Any]) -> str:
        rows = []
        for location, key in (("path", "path_params"), ("query", "query_params"), ("header", "headers")):
            for param in endpoint.get(key, []) or []:
                rows.append(
                    f"<tr><td><code>{escape(str(param.get('name', '')))}</code></td><td>{location}</td><td><code>{escape(DocumentationGenerator._schema_type(param))}</code></td><td>{DocumentationGenerator._required_badge(bool(param.get('required')))}</td><td>{escape(DocumentationGenerator._schema_constraints(param))}</td></tr>"
                )
        if not rows:
            return ""
        return f"""<details class="detail-section" open>
      <summary>Parameters</summary>
      <div class="section-content"><table><thead><tr><th>Name</th><th>In</th><th>Type</th><th>Required</th><th>Constraints</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>
    </details>"""

    @staticmethod
    def _html_request_body(endpoint: Dict[str, Any]) -> str:
        request_body = endpoint.get("request_body")
        if not request_body:
            return ""
        block_id = DocumentationGenerator._stable_dom_id("body", endpoint)
        sample = DocumentationGenerator._sample_from_schema(request_body.get("schema"))
        return f"""<details class="detail-section" open>
      <summary>Request Body</summary>
      <div class="section-content"><p class="section-label">Model</p><code>{escape(str(request_body.get('model', 'object')))}</code>{DocumentationGenerator._html_schema(request_body.get('schema'))}<p class="section-label">Example</p><div class="section-tools"><button class="tool-btn" onclick="copyBlock('{block_id}')">Copy body</button></div><pre class="json" id="{block_id}">{escape(json.dumps(sample, indent=2))}</pre></div>
    </details>"""

    @staticmethod
    def _html_pagination(endpoint: Dict[str, Any]) -> str:
        pagination = DocumentationGenerator._pagination_info(endpoint)
        if not pagination:
            return ""
        if pagination["detected"]:
            rows = "".join(
                f"<tr><td><code>{escape(str(param.get('name', '')))}</code></td><td><code>{escape(DocumentationGenerator._schema_type(param))}</code></td><td>{DocumentationGenerator._required_badge(bool(param.get('required')))}</td></tr>"
                for param in pagination["params"]
            )
            content = f"<table><thead><tr><th>Parameter</th><th>Type</th><th>Required</th></tr></thead><tbody>{rows}</tbody></table>"
        else:
            content = '<p class="section-desc">This looks like a list endpoint, but no explicit pagination parameters were detected. Add limit, offset, page, or cursor metadata before high-volume production use.</p>'
        return f"""<details class="detail-section" open>
      <summary>Pagination</summary>
      <div class="section-content">{content}</div>
    </details>"""

    @staticmethod
    def _html_request_example(endpoint: Dict[str, Any]) -> str:
        block_id = DocumentationGenerator._stable_dom_id("curl", endpoint)
        return f"""<details class="detail-section" open>
      <summary>Request Example</summary>
      <div class="section-content"><div class="section-tools"><button class="tool-btn" onclick="copyBlock('{block_id}')">Copy curl</button></div><pre class="json" id="{block_id}">{escape(DocumentationGenerator._curl_example(endpoint))}</pre></div>
    </details>"""

    @staticmethod
    def _html_responses(endpoint: Dict[str, Any]) -> str:
        items = []
        for response in DocumentationGenerator._success_responses(endpoint):
            if DocumentationGenerator._status_code(response) == 204:
                items.append(
                    f"""<div class="response-item"><strong class="response-code">204</strong><p class="response-desc">{escape(str(response.get('description') or 'No Content'))}</p></div>"""
                )
                continue
            example = DocumentationGenerator._sample_from_schema(response.get("schema"))
            # Only show example if schema was detected (example is not None)
            example_html = ""
            if example is not None:
                example_html = f"""<p class="section-label">Example</p><pre class="json">{escape(json.dumps(example, indent=2))}</pre>"""
            else:
                example_html = f"""<p class="section-label">Response schema not detected in source code</p>"""
            items.append(
                f"""<div class="response-item"><strong class="response-code">{escape(str(response.get('status_code', 200)))}</strong><p class="response-desc">{escape(str(response.get('description') or response.get('message') or 'Response'))}</p>{DocumentationGenerator._html_schema(response.get('schema'))}{example_html}</div>"""
            )
        if not items:
            return ""
        return f"""<details class="detail-section" open>
      <summary>Success Responses</summary>
      <div class="section-content">{''.join(items)}</div>
    </details>"""

    @staticmethod
    def _html_schema(schema: Dict[str, Any]) -> str:
        schema = DocumentationGenerator._schema_object(schema)
        if not schema or not schema.get("properties"):
            return ""

        required = set(schema.get("required", []))
        rows = []
        for field, field_schema in schema.get("properties", {}).items():
            rows.append(
                f"<tr><td><code>{escape(str(field))}</code></td><td><code>{escape(DocumentationGenerator._schema_type(field_schema))}</code></td><td>{DocumentationGenerator._required_badge(field in required)}</td><td>{escape('Yes' if field_schema.get('nullable') else 'No')}</td><td>{escape(DocumentationGenerator._schema_constraints(field_schema))}</td><td>{escape(DocumentationGenerator._schema_enum(field_schema))}</td></tr>"
            )
        return f"""<p class="section-label">Schema</p><table><thead><tr><th>Field</th><th>Type</th><th>Required</th><th>Nullable</th><th>Constraints</th><th>Enum</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"""

    @staticmethod
    def _html_ai_notes(endpoint: Dict[str, Any]) -> str:
        ai_notes = endpoint.get("ai_notes")
        if not ai_notes:
            return ""

        items = []
        for label, key in (("Request", "request"), ("Response", "response"), ("Errors", "errors")):
            value = ai_notes.get(key)
            if value:
                items.append(f"<li><strong>{label}:</strong> {escape(str(value))}</li>")

        if not items:
            return ""
        return f"""<details class="detail-section">
      <summary>AI Notes</summary>
      <div class="section-content"><ul>{''.join(items)}</ul></div>
    </details>"""

    @staticmethod
    def _overview_section(endpoints: List[Dict[str, Any]], title: str) -> str:
        methods = sorted({str(endpoint.get("method", "GET")).upper() for endpoint in endpoints})
        # Extract frameworks from provenance or direct field
        frameworks = set()
        for endpoint in endpoints:
            framework = DocumentationGenerator._get_framework(endpoint)
            if framework and framework != "Unknown":
                frameworks.add(framework)
        frameworks = sorted(frameworks)
        sources = sorted({str(endpoint.get("source_file", "unknown")) for endpoint in endpoints if endpoint.get("source_file")})
        return f"""
<div class="doc-section" id="section-overview">
  <div class="section-header">API Overview</div>
  <div class="overview-grid">
    <div class="ov-card"><span class="ov-label">API Name</span><span class="ov-value">{escape(title)}</span></div>
    <div class="ov-card"><span class="ov-label">Total Endpoints</span><span class="ov-value">{len(endpoints)}</span></div>
    <div class="ov-card"><span class="ov-label">Methods</span><span class="ov-value">{escape(", ".join(methods) or "None")}</span></div>
    <div class="ov-card"><span class="ov-label">Frameworks</span><span class="ov-value">{escape(", ".join(frameworks) or "Unknown")}</span></div>
    <div class="ov-card"><span class="ov-label">Source Files</span><span class="ov-value">{len(sources)}</span></div>
    <div class="ov-card full-width"><span class="ov-label">Description</span><span class="ov-value">This documentation was generated from detected route definitions and enriched endpoint metadata.</span></div>
  </div>
</div>
"""

    @staticmethod
    def _support_sections(endpoints: List[Dict[str, Any]]) -> str:
        # This generator must not emit synthetic/global recommendations (headers, changelog,
        # generic error tables, testing flows). Those should be extracted from source or omitted.
        return ""

    @staticmethod
    def _sidebar_groups(endpoints: List[Dict[str, Any]]) -> str:
        groups: Dict[str, List[Tuple[int, Dict[str, Any]]]] = {}
        for idx, endpoint in enumerate(endpoints):
            group_name = DocumentationGenerator._group_name(str(endpoint.get("path", "/")))
            groups.setdefault(group_name, []).append((idx, endpoint))

        html_groups = []
        for group_idx, (group_name, group_items) in enumerate(sorted(groups.items())):
            item_html = []
            for endpoint_idx, endpoint in group_items:
                method = str(endpoint.get("method", "GET")).upper()
                path = escape(str(endpoint.get("path", "/")))
                item_html.append(
                    f"""<li class="nav-item"><a href="#endpoint-{endpoint_idx}"><span class="method-badge {DocumentationGenerator._method_badge_class(method)}">{escape(method)}</span><span>{path}</span></a></li>"""
                )
            html_groups.append(
                f"""<div class="menu-group">
      <button class="group-toggle" onclick="toggleGroup({group_idx})"><span class="toggle-arrow" id="arrow-{group_idx}">&gt;</span><span>{escape(group_name)}</span><span class="badge-count">{len(group_items)}</span></button>
      <ul class="group-items show" id="items-{group_idx}">{''.join(item_html)}</ul>
    </div>"""
            )
        return "\n".join(html_groups)

    @staticmethod
    def _group_name(path: str) -> str:
        parts = [part for part in path.split("/") if part and not part.startswith("{")]
        if not parts:
            return "Root"
        return parts[0].replace("-", " ").replace("_", " ").title()

    @staticmethod
    def _sort_endpoints(endpoints: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        method_order = {"GET": 0, "POST": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}
        return sorted(
            endpoints,
            key=lambda item: (
                "/".join(part for part in str(item.get("path", "/")).split("/") if part and not part.startswith("{")),
                method_order.get(str(item.get("method", "GET")).upper(), 99),
                str(item.get("path", "/")),
            ),
        )

    @staticmethod
    def _method_badge_class(method: str) -> str:
        method = method.lower()
        return f"badge-{method}" if method in {"get", "post", "put", "delete", "patch"} else "badge-other"

    @staticmethod
    def _friendly_summary(method: str, path: str) -> str:
        resource = DocumentationGenerator._group_name(path)
        verbs = {
            "GET": "List" if "{" not in path else "Get",
            "POST": "Create",
            "PUT": "Update",
            "PATCH": "Partially update",
            "DELETE": "Delete",
        }
        return f"{verbs.get(method, method.title())} {resource}"

    @staticmethod
    def _success_responses(endpoint: Dict[str, Any]) -> List[Dict[str, Any]]:
        responses = endpoint.get("responses", []) or []
        success = [
            response for response in responses
            if DocumentationGenerator._status_code(response) < 400
        ]
        return success

    @staticmethod
    def _error_responses(endpoint: Dict[str, Any]) -> List[Dict[str, Any]]:
        responses = endpoint.get("responses", []) or []
        return [
            response for response in responses
            if DocumentationGenerator._status_code(response) >= 400
        ]

    @staticmethod
    def _status_code(response: Dict[str, Any]) -> int:
        try:
            return int(response.get("status_code", 200) or 200)
        except (TypeError, ValueError):
            return 200

    @staticmethod
    def _pagination_info(endpoint: Dict[str, Any]) -> Dict[str, Any]:
        method = str(endpoint.get("method", "GET")).upper()
        if method != "GET":
            return {}

        explicit = endpoint.get("x-pagination")
        if explicit:
            params = [
                param for param in endpoint.get("query_params", []) or []
                if str(param.get("name", "")).lower() in {"limit", "offset", "page", "page_size", "per_page", "cursor", "next_cursor", "after", "before"}
            ]
            return {"detected": bool(explicit.get("detected", True)), "params": params, "source": explicit.get("source")}

        pagination_names = {"limit", "offset", "page", "page_size", "per_page", "cursor", "next_cursor", "after", "before"}
        params = [
            param for param in endpoint.get("query_params", []) or []
            if str(param.get("name", "")).lower() in pagination_names
        ]
        if params:
            return {"detected": True, "params": params}

        response_is_array = any(
            str((response.get("schema") or {}).get("type", "")).lower() == "array"
            for response in endpoint.get("responses", []) or []
        )
        if response_is_array:
            return {"detected": False, "params": []}
        return {}

    @staticmethod
    def _detected_pagination_params(endpoints: List[Dict[str, Any]]) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for endpoint in endpoints:
            pagination = DocumentationGenerator._pagination_info(endpoint)
            if not pagination.get("detected"):
                continue
            for param in pagination.get("params", []):
                name = str(param.get("name", ""))
                counts[name] = counts.get(name, 0) + 1
        return dict(sorted(counts.items()))

    @staticmethod
    def _curl_example(endpoint: Dict[str, Any]) -> str:
        method = str(endpoint.get("method", "GET")).upper()
        path = DocumentationGenerator._sample_path(str(endpoint.get("path", "/")))
        query_params = endpoint.get("query_params", []) or []
        if query_params:
            query = "&".join(
                f"{param.get('name')}={DocumentationGenerator._sample_query_value(param)}"
                for param in query_params
                if param.get("name")
            )
            if query:
                path = f"{path}?{query}"

        request_body = endpoint.get("request_body") or {}
        body = DocumentationGenerator._sample_from_schema(request_body.get("schema"))
        has_body = method in {"POST", "PUT", "PATCH"} and bool(request_body)
        lines = [
            f'curl -i -X {method} "$API_BASE{path}"',
            '  -H "Accept: application/json"',
        ]
        if has_body:
            lines.append('  -H "Content-Type: application/json"')
            lines.append("  -d '" + json.dumps(body, indent=2) + "'")
        return " \\\n".join(lines)

    @staticmethod
    def _sample_path(path: str) -> str:
        import re

        return re.sub(r"\{[^}]+\}", "123", path)

    @staticmethod
    def _sample_query_value(param: Dict[str, Any]) -> str:
        name = str(param.get("name", "")).lower()
        if name in {"limit", "page_size", "per_page"}:
            return "20"
        if name in {"offset", "page"}:
            return "1"
        if "cursor" in name:
            return "cursor_123"
        return str(DocumentationGenerator._sample_value(DocumentationGenerator._schema_type(param), name))

    @staticmethod
    def _stable_dom_id(prefix: str, endpoint: Dict[str, Any]) -> str:
        raw = f"{prefix}-{endpoint.get('method', 'GET')}-{endpoint.get('path', '/')}"
        safe = "".join(ch.lower() if ch.isalnum() else "-" for ch in raw)
        while "--" in safe:
            safe = safe.replace("--", "-")
        return safe.strip("-")

    @staticmethod
    def _sample_from_schema(schema: Dict[str, Any]) -> Any:
        # DO NOT fabricate examples - only generate if schema is explicitly detected
        if not schema:
            return None  # Return None instead of fabricated {"message": "Success"}
        schema_type = str(schema.get("type", "object")).lower()
        if schema_type == "array":
            return [DocumentationGenerator._sample_from_schema(schema.get("items") or {"type": "object"})]
        if not schema.get("properties"):
            return DocumentationGenerator._sample_value(schema_type, "value")
        sample = {}
        for name, field_schema in schema.get("properties", {}).items():
            sample[name] = DocumentationGenerator._sample_from_schema(field_schema)
        return sample

    @staticmethod
    def _sample_value(field_type: str, name: str) -> Any:
        lowered = f"{field_type} {name}".lower()
        if "array" in lowered:
            return []
        if "object" in lowered:
            return {}
        if "int" in lowered or "number" in lowered or "float" in lowered or "decimal" in lowered:
            return 1
        if "bool" in lowered:
            return True
        if "email" in lowered:
            return "user@example.com"
        if "date" in lowered or "time" in lowered:
            return "2026-05-25"
        if "id" in lowered:
            return "123"
        return "string"

    @staticmethod
    def _schema_type(schema: Dict[str, Any]) -> str:
        if not schema:
            return "string"
        for key in ("python_type", "typescript_type", "java_type", "type"):
            if schema.get(key):
                value = schema.get(key)
                if isinstance(value, list):
                    return " | ".join(str(item) for item in value)
                return str(value)
        return "string"

    @staticmethod
    def _schema_object(schema: Dict[str, Any]) -> Dict[str, Any]:
        if not schema:
            return {}
        if str(schema.get("type", "")).lower() == "array":
            items = schema.get("items") or {}
            if items.get("properties"):
                return items
        return schema

    @staticmethod
    def _schema_constraints(schema: Dict[str, Any]) -> str:
        if not schema:
            return "-"
        constraints = []
        for key in (
            "minimum",
            "maximum",
            "exclusiveMinimum",
            "exclusiveMaximum",
            "minLength",
            "maxLength",
            "minItems",
            "maxItems",
            "pattern",
            "format",
            "default",
        ):
            if key in schema and schema.get(key) is not None:
                constraints.append(f"{key}: `{schema.get(key)}`")
        return ", ".join(constraints) or "-"

    @staticmethod
    def _schema_enum(schema: Dict[str, Any]) -> str:
        enum_values = schema.get("enum") if schema else None
        if not enum_values:
            return "-"
        return ", ".join(f"`{value}`" for value in enum_values)

    @staticmethod
    def _html_error_responses(endpoint: Dict[str, Any]) -> str:
        errors = DocumentationGenerator._error_responses(endpoint)
        # DO NOT fabricate error responses - only show if detected
        if not errors:
            return f"""<details class="detail-section">
      <summary>Error Responses</summary>
      <div class="section-content"><p class="section-label">No error responses were detected in source code.</p></div>
    </details>"""
        items = []
        for response in errors:
            items.append(
                f"""<div class="response-item"><strong class="response-code error-code">{escape(str(response.get('status_code')))}</strong><p class="response-desc">{escape(str(response.get('description') or response.get('message') or 'Error response'))}</p></div>"""
            )
        return f"""<details class="detail-section">
      <summary>Error Responses</summary>
      <div class="section-content">{''.join(items)}</div>
    </details>"""

    @staticmethod
    def _sample_error() -> Dict[str, Any]:
        # Removed: previously emitted synthetic error payloads.
        return {}

    @staticmethod
    def _required_badge(required: bool) -> str:
        if required:
            return '<span class="req-yes">Required</span>'
        return '<span class="req-no">Optional</span>'

    @staticmethod
    def _sort_endpoints(endpoints: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        method_order = {"GET": 0, "POST": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}
        return sorted(
            endpoints,
            key=lambda endpoint: (
                DocumentationGenerator._resource_key(str(endpoint.get("path", "/"))),
                method_order.get(str(endpoint.get("method", "GET")).upper(), 99),
                str(endpoint.get("path", "/")),
            ),
        )

    @staticmethod
    def _resource_key(path: str) -> str:
        return "/".join(part for part in path.split("/") if part and not part.startswith("{"))


    @staticmethod
    def _get_framework(endpoint: Dict[str, Any]) -> str:
        """Extract framework from endpoint provenance or direct field."""
        # First check provenance (new structure)
        provenance = endpoint.get("provenance", {})
        if isinstance(provenance, dict):
            framework = provenance.get("framework")
            if framework:
                return framework
        
        # Fallback to direct framework field (old structure)
        framework = endpoint.get("framework")
        if framework:
            return framework
        
        return "Unknown"

    @staticmethod
    def _get_handler(endpoint: Dict[str, Any]) -> str:
        """Extract handler information from endpoint."""
        # Check handler object
        handler = endpoint.get("handler", {})
        if isinstance(handler, dict):
            class_name = handler.get("class")
            method_name = handler.get("method")
            if class_name and method_name:
                return f"{class_name}@{method_name}"
            elif class_name:
                return class_name
        
        # Fallback to function_name field
        function_name = endpoint.get("function_name")
        if function_name:
            return function_name
        
        return "unknown"

    @staticmethod
    def _get_source(endpoint: Dict[str, Any]) -> str:
        """Extract source file information from endpoint."""
        # Check provenance first (new structure)
        provenance = endpoint.get("provenance", {})
        if isinstance(provenance, dict):
            source_file = provenance.get("source_file")
            if source_file:
                return source_file
        
        # Fallback to direct source_file field
        source = endpoint.get("source", {})
        if isinstance(source, dict):
            source_file = source.get("file")
            if source_file:
                return source_file
        
        source_file = endpoint.get("source_file")
        if source_file:
            return source_file
        
        return "unknown"

    @staticmethod
    def _html_status_codes(endpoint: Dict[str, Any]) -> str:
        """Generate HTML for status codes section."""
        status_codes = endpoint.get("statusCodes", [])
        if not status_codes:
            return ""
        
        rows = []
        for code in sorted(status_codes):
            if 200 <= code < 300:
                badge_class = "response-code"
                description = DocumentationGenerator._status_code_description(code)
            elif 300 <= code < 400:
                badge_class = "response-code"
                description = DocumentationGenerator._status_code_description(code)
            elif 400 <= code < 500:
                badge_class = "error-code"
                description = DocumentationGenerator._status_code_description(code)
            else:
                badge_class = "error-code"
                description = DocumentationGenerator._status_code_description(code)
            
            rows.append(f"<tr><td><strong class='{badge_class}'>{code}</strong></td><td>{escape(description)}</td></tr>")
        
        if not rows:
            return ""
        
        return f"""<details class="detail-section" open>
      <summary>Status Codes</summary>
      <div class="section-content"><table><thead><tr><th>Code</th><th>Description</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>
    </details>"""

    @staticmethod
    def _html_path_parameters(endpoint: Dict[str, Any]) -> str:
        """Generate HTML for path parameters section."""
        path_params = endpoint.get("pathParameters", [])
        if not path_params:
            return ""
        
        rows = []
        for param in path_params:
            rows.append(
                f"<tr><td><code>{escape(str(param.get('name', '')))}</code></td><td><code>{escape(str(param.get('type', 'string')))}</code></td><td>{escape(str(param.get('description', '')))}</td></tr>"
            )
        
        return f"""<details class="detail-section" open>
      <summary>Path Parameters</summary>
      <div class="section-content"><table><thead><tr><th>Name</th><th>Type</th><th>Description</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>
    </details>"""

    @staticmethod
    def _html_security(endpoint: Dict[str, Any]) -> str:
        """Generate HTML for security/authentication section."""
        security = endpoint.get("security", [])
        if not security:
            return ""
        
        items = []
        for auth_method in security:
            items.append(f"<li>{escape(str(auth_method))}</li>")
        
        return f"""<details class="detail-section" open>
      <summary>Authentication</summary>
      <div class="section-content"><ul>{''.join(items)}</ul></div>
    </details>"""

    @staticmethod
    def _status_code_description(code: int) -> str:
        """Get description for HTTP status code."""
        descriptions = {
            200: "OK - Request succeeded",
            201: "Created - Resource created successfully",
            202: "Accepted - Request accepted for processing",
            204: "No Content - Request succeeded with no content",
            301: "Moved Permanently - Resource moved",
            302: "Found - Resource found at different location",
            304: "Not Modified - Resource not modified",
            400: "Bad Request - Invalid request",
            401: "Unauthorized - Authentication required",
            403: "Forbidden - Access denied",
            404: "Not Found - Resource not found",
            409: "Conflict - Request conflicts with current state",
            422: "Unprocessable Entity - Validation failed",
            429: "Too Many Requests - Rate limit exceeded",
            500: "Internal Server Error - Server error",
            502: "Bad Gateway - Invalid response from upstream",
            503: "Service Unavailable - Server temporarily unavailable",
        }
        return descriptions.get(code, f"HTTP {code}")
